name: Digger

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: digger run
        uses: diggerhq/digger@v0.1.32
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCK_PROVIDER: azure
          DIGGER_AZURE_AUTH_METHOD: CONNECTION_STRING
          DIGGER_AZURE_CONNECTION_STRING: ${{ secrets.DIGGER_AZURE_CONNECTION_STRING }}
          DIGGER_BACKEND_ARM_ACCESS_KEY: ${{ secrets.DIGGER_BACKEND_ARM_ACCESS_KEY }}
          DTF_DNS_CLOUDFLARE_API_KEY: ${{ secrets.DTF_DNS_CLOUDFLARE_API_KEY }}
          DTF_DNS_CLOUDFLARE_EMAIL: ${{ secrets.DTF_DNS_CLOUDFLARE_EMAIL }}
          DTF_GITHUB_GITHUB_TOKEN: ${{ secrets.DTF_GITHUB_GITHUB_TOKEN }}